<a href="https://colab.research.google.com/github/Nusrat-2808/google-colab/blob/main/Operations_using_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
data_type=[('name','U15'),('class',int),('roll_no',int),('fav_subject','U15')]
students_details=[('James',8,1,'PHYSICS'),
             ('Nail',8,2,'HISTORY'),
             ('Paul',8,3,'BIOLOGY'),
             ('Pit',8,4,'MATH'),
             ('Alice',8,5,'ENGLISH')]

In [ ]:
students=np.array(students_details,dtype=data_type)
print(students)

[('James', 8, 1, 'PHYSICS') ('Nail', 8, 2, 'HISTORY')
 ('Paul', 8, 3, 'BIOLOGY') ('Pit', 8, 4, 'MATH')
 ('Alice', 8, 5, 'ENGLISH')]


In [ ]:
student1=np.sort(students,order='name')
print(student1)

[('Alice', 8, 5, 'ENGLISH') ('James', 8, 1, 'PHYSICS')
 ('Nail', 8, 2, 'HISTORY') ('Paul', 8, 3, 'BIOLOGY') ('Pit', 8, 4, 'MATH')]


In [ ]:
student2=np.reshape(students,(5,1))
print(student2)

[[('James', 8, 1, 'PHYSICS')]
 [('Nail', 8, 2, 'HISTORY')]
 [('Paul', 8, 3, 'BIOLOGY')]
 [('Pit', 8, 4, 'MATH')]
 [('Alice', 8, 5, 'ENGLISH')]]


In [ ]:
import numpy as np
arr=np.array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
arr_copy=arr.copy()
for x in arr_copy:
    if x%2==1:
        arr_copy[x]=-1
print(arr_copy)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [ ]:
arr2=arr.reshape(2,5)
print(arr2)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [ ]:
x=0
for i in arr:
  x=x+i
print(x)

45


In [ ]:
sum=0
for j in arr:
  if j%2==0:
    sum=sum+j
print(sum)

20
