<a href="https://colab.research.google.com/github/Nusrat-2808/google-colab/blob/main/Welcome_to_data_science.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ACTIVITY 1

In [ ]:
import numpy as np

In [ ]:
a=np.arange(9,dtype=np.float64).reshape(3,3)
print("FIRST ARRAY:")
print(a)
print('\n')

FIRST ARRAY:
[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]




In [ ]:
b=np.array([10,10,10])
print("SECOND ARRAY:")
print(b)
print('\n')

SECOND ARRAY:
[10 10 10]




In [ ]:
print("ADD THE TWO ARRAYS:")
print(np.add(a,b))
print('\n')

ADD THE TWO ARRAYS:
[[10. 11. 12.]
 [13. 14. 15.]
 [16. 17. 18.]]




In [ ]:
print("SUBTRACT THE TWO ARRAYS:")
print(np.subtract(a,b))
print('\n')

SUBTRACT THE TWO ARRAYS:
[[-10.  -9.  -8.]
 [ -7.  -6.  -5.]
 [ -4.  -3.  -2.]]




In [ ]:
print("MULTIPLY THE TWO ARRAYS:")
print(np.multiply(a,b))
print('\n')

MULTIPLY THE TWO ARRAYS:
[[ 0. 10. 20.]
 [30. 40. 50.]
 [60. 70. 80.]]




In [ ]:
print("DIVIDE THE TWO ARRAYS:")
print(np.divide(a,b))
print('\n')

DIVIDE THE TWO ARRAYS:
[[0.  0.1 0.2]
 [0.3 0.4 0.5]
 [0.6 0.7 0.8]]




# ACTIVITY 2

In [ ]:
import numpy as np

In [ ]:
#DEFINE THE STRUCTURED DATA
data_type=[('name','U15'),('class',int),('height',float)]
#define student details
students_details=[('James',5,48.5),
                  ('Nail',6,52.5),
                  ('Paul',5,42.10),
                  ('Pit',5,40.11)]

In [ ]:
#create a structured numpy array
students=np.array(students_details,dtype=data_type)
#print the original array
print("ORIGINAL ARRAY:")
print(students)

ORIGINAL ARRAY:
[('James', 5, 48.5 ) ('Nail', 6, 52.5 ) ('Paul', 5, 42.1 )
 ('Pit', 5, 40.11)]


In [ ]:
#sort by height
print("\n Sort by height:")
print(np.sort(students,order='height'))


 Sort by height:
[('Pit', 5, 40.11) ('Paul', 5, 42.1 ) ('James', 5, 48.5 )
 ('Nail', 6, 52.5 )]


In [ ]:
#sort by class
print("\n Sort by class:")
print(np.sort(students,order='class'))


 Sort by class:
[('James', 5, 48.5 ) ('Paul', 5, 42.1 ) ('Pit', 5, 40.11)
 ('Nail', 6, 52.5 )]


In [ ]:
#sort by height
print("Students with more than height 50:")
student2=students[students['height']>50]
print(student2)

Students with more than height 50:
[('Nail', 6, 52.5)]
